### ISSUE TITLE
运行ffmpeg.probe，报错FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by one-tree** [baotlake/Screenshot-Splicing#1]
你好，感谢你的分享，我在运行代码时，ffmpeg.probe函数报错FileNotFoundError: [WinError 2] 系统找不到指定的文件。
在网上看了一些解决方法都没有解决，而且ffmpeg.input不会报这个错。
请问你那儿有遇到过类似问题吗？

**Comment by baotlake** [comment]
Hi
ffmpeg-python 依赖ffmpeg，pip install ffmpeg-python 不会安装ffmpeg，ffmpeg需要另外安装。

安装ffmpeg后，可以用ffprobe, ffmpeg 这两个命令行命令试一下，确认ffmpeg这两个命令可用后再运行试一下呢
